// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv8NjM2V7PamrYeOxre330niPqXCjtIjM',
    appId: '1:596252682714:web:bdc29474c7f48ba92038e3',
    messagingSenderId: '596252682714',
    projectId: 'fir-testapp-b3582',
    authDomain: 'fir-testapp-b3582.firebaseapp.com',
    storageBucket: 'fir-testapp-b3582.firebasestorage.app',
    measurementId: 'G-7E2FD32B3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlu8dVXWag9tp6IBvhdt2pZfPBVi3N4IQ',
    appId: '1:596252682714:android:b30efc1083e130922038e3',
    messagingSenderId: '596252682714',
    projectId: 'fir-testapp-b3582',
    storageBucket: 'fir-testapp-b3582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2A56dfIU320OApGhjyXNyxebeHSh5Awg',
    appId: '1:596252682714:ios:8e8426be2fa2f1762038e3',
    messagingSenderId: '596252682714',
    projectId: 'fir-testapp-b3582',
    storageBucket: 'fir-testapp-b3582.firebasestorage.app',
    iosBundleId: 'com.example.firebasetestapp',
  );
}
